/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  es: {
    modulesSection: 'MÓDULOS',
    managementSection: 'GESTIÓN',
    adminSection: 'ADMINISTRACIÓN',
    dashboard: 'Dashboard',
    bookings: 'Reservas',
    tours: 'Excursiones',
    customers: 'Clientes',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    notificaciones: 'Notificaciones',
    marcarLeidas: 'Marcar leídas',
    limpiar: 'Limpiar',
    sinNotificaciones: 'No tienes notificaciones.',
    reservasTitle: 'Gestión de Reservas',
    settingsTitle: 'Configuración del Sistema',
    dashboardTitle: 'Resumen General',
    adminPanel: 'Panel de administración',
    notifications: 'Notificaciones',
    seeAll: 'Ver todas',
    myProfile: 'Mi Perfil',
    general: 'General',
    appearance: 'Apariencia',
    security: 'Seguridad',
    profile: 'Perfil',
    search: 'Buscar',
    actions: 'Acciones',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    create: 'Crear',
    update: 'Actualizar',
    active: 'Activo',
    inactive: 'Inactivo',
    all: 'Todas',
    paid: 'Pagado',
    pending: 'Pendiente',
    canceled: 'Cancelado',
    new: 'Nuevo',
    vip: 'VIP',
    status: 'Estado',
    customer: 'Cliente',
    customersTitle: 'Gestión de Clientes',
    customersSubtitle: 'Directorio de clientes e historial de reservas.',
    newCustomer: 'Nuevo Cliente',
    editCustomer: 'Editar Cliente',
    customerProfile: 'Perfil del Cliente',
    customerSaved: 'Cliente guardado correctamente',
    customerDeleted: 'Cliente eliminado',
    fullName: 'Nombre completo',
    contact: 'Contacto',
    country: 'País',
    countryOrigin: 'País de origen',
    totalBookings: 'Total de reservas',
    totalSpent: 'Total gastado',
    lastVisit: 'Última visita',
    searchCustomers: 'Buscar por nombre, email o país...',
    deleteCustomerTitle: '¿Eliminar Cliente?',
    deleteCustomerText: 'Esta acción borrará el cliente seleccionado. ¿Estás seguro?',
    bookingsTitle: 'Gestión de Reservas',
    bookingsSubtitle: 'Administra todas las reservas del sistema contable.',
    newBooking: 'Nueva Reserva',
    editBooking: 'Editar Reserva',
    bookingDetail: 'Detalle de Reserva',
    bookingSaved: 'Reserva guardada correctamente',
    bookingDeleted: 'Reserva eliminada',
    searchBookings: 'Buscar reservas...',
    bookingId: 'ID',
    tour: 'Tour',
    date: 'Fecha',
    pax: 'Pax',
    people: 'Personas',
    hotel: 'Hotel',
    amount: 'Monto',
    totalAmount: 'Monto total',
    notes: 'Notas',
    noNotes: 'Sin notas adicionales.',
    customerName: 'Nombre Cliente',
    paymentStatus: 'Estado Pago',
    pickup: 'Hotel / Recogida',
    saveBooking: 'Guardar Reserva',
    deleteBookingTitle: '¿Eliminar Reserva?',
    deleteBookingText: 'Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar la reserva',
    toursTitle: 'Gestión de Excursiones',
    toursSubtitle: 'Añade, edita o desactiva los tours disponibles en la web.',
    newTour: 'Nuevo Tour',
    editTour: 'Editar Tour',
    tourSaved: 'Tour guardado correctamente',
    tourDeleted: 'Tour eliminado correctamente',
    tourStatusUpdated: 'Estado del tour actualizado',
    searchTours: 'Buscar excursión...',
    category: 'Categoría',
    duration: 'Duración',
    rating: 'Calificación',
    adultPrice: 'Precio Adulto',
    childPrice: 'Precio Niño',
    imageUrl: 'URL de imagen',
    description: 'Descripción',
    includes: 'Incluye',
    title: 'Título',
    island: 'Isla',
    adventure: 'Aventura',
    culture: 'Cultura',
    nature: 'Naturaleza',
    halfDay: 'Medio Día',
    fullDay: 'Día Completo',
    deleteTourTitle: '¿Eliminar Tour?',
    deleteTourText: 'Esta acción no se puede deshacer. Se ocultará de la web principal.',
    systemPreferences: 'Administra las preferencias del sistema y tu cuenta.',
    companyInfo: 'Información de la Empresa',
    companyName: 'Nombre de la Empresa',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    website: 'Sitio Web',
    currency: 'Moneda Principal',
    saveChanges: 'Guardar Cambios',
    visualCustomization: 'Personalización Visual',
    systemTheme: 'Tema del Sistema',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    darkModeDesc: 'Cambia la apariencia del panel a colores oscuros.',
    primaryColor: 'Color Principal',
    panelLanguage: 'Idioma del Panel',
    panelLanguageDesc: 'Elige el idioma de la interfaz del sistema.',
    spanish: 'Español',
    english: 'English',
    notifPreferences: 'Preferencias de Notificación',
    accountSecurity: 'Seguridad de la Cuenta',
    activeSessions: 'Sesiones Activas',
    currentSession: 'Actual',
    closeSession: 'Cerrar Sesión',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Nueva Contraseña',
    updatePassword: 'Actualizar Contraseña',
    passwordUpdated: 'Contraseña actualizada correctamente',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres',
    currentPasswordRequired: 'Escribe la contraseña actual',
    preferenceUpdated: 'Preferencia actualizada',
    colorUpdated: 'Color actualizado',
    changesSaved: 'Cambios guardados',
    sessionClosed: 'Sesión cerrada',
    role: 'Cargo',
    department: 'Departamento',
    lastAccess: 'Último acceso',
    accessLevel: 'Nivel de acceso',
    accountData: 'Datos de la cuenta',
    emailNotifications: 'Notificaciones por Email',
    emailNotificationsDesc: 'Recibe un correo diario con el resumen de reservas.',
    newBookingAlerts: 'Alertas de Nueva Reserva',
    newBookingAlertsDesc: 'Notificación instantánea cuando un cliente hace una reserva.',
    paymentAlerts: 'Alertas de Pago',
    paymentAlertsDesc: 'Avisos cuando se confirma un pago mediante tarjeta.',
    pushNotifications: 'Notificaciones Push',
    pushNotificationsDesc: 'Notificaciones en el navegador.',
    browserPermissionGranted: 'Permiso de notificaciones activado',
    browserPermissionDenied: 'El navegador no permitió las notificaciones',
    browserPermissionUnsupported: 'Este navegador no soporta notificaciones push',
    dashboardSummary: 'Resumen del Panel',
    dashboardWelcome: 'Bienvenido de nuevo, aquí tienes el estado de Jhoraji Tours.',
    downloadReport: 'Descargar Reporte',
    reportGenerated: 'Reporte generado exitosamente',
    totalRevenue: 'Ingresos Totales',
    todayBookings: 'Reservas Hoy',
    newCustomers: 'Nuevos Clientes',
    activeTours: 'Tours Activos',
    thisMonth: 'este mes',
    recentBookings: 'Reservas Recientes',
    popularTours: 'Excursiones Populares',
    loginSubtitle: 'Sistema de Reservas y Contabilidad',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    login: 'Iniciar Sesión',
    loginSuccess: 'Inicio de sesión exitoso',
    loginError: 'Correo o contraseña incorrectos. Por favor, intenta de nuevo.',
    forgotCredentials: '¿Olvidaste tus credenciales?',
    contactSupport: 'Contacta al soporte técnico',
    usdCurrency: 'USD - Dólar Estadounidense',
    eurCurrency: 'EUR - Euro',
    dopCurrency: 'DOP - Peso Dominicano',
    sales: 'ventas',
    noCustomersFound: 'No se encontraron clientes.',
    permissions: 'Permisos',
    permissionsDesc: 'Gestiona el acceso a los módulos según el rol.',
    selectCountry: 'Seleccione un país',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Reservas',
    moduleTours: 'Excursiones',
    moduleCustomers: 'Clientes',
    moduleSettings: 'Configuración',
    moduleUsers: 'Usuarios',
    moduleDrivers: 'Choferes',
    moduleProviders: 'Proveedores',
    moduleAgencies: 'Agencias',
    moduleActivities: 'Actividades',
    moduleSchedule: 'Horario',
    moduleFinances: 'Finanzas & Liquidación',
    moduleAudit: 'Auditoría',
    moduleOrders: 'Órdenes',
    roleOperator: 'Operador de Reservas',
    roleAgent: 'Agente de Ventas',
    moduleAccess: 'Acceso a Módulos',
    actionPermissions: 'Permisos de Acciones',
    actionCreate: 'Crear registros',
    actionEdit: 'Editar registros',
    actionDelete: 'Eliminar registros',
    showing: 'Mostrando',
    to: 'a',
    of: 'de',
    previous: 'Anterior',
    next: 'Siguiente',
    auditTitle: 'Auditoría del Sistema',
    auditSubtitle: 'Registro de todas las acciones realizadas en el sistema',
    update: 'Actualizar',
    clearLog: 'Limpiar',
    totalActions: 'Total Acciones',
    creations: 'Creaciones',
    editions: 'Ediciones',
    deletions: 'Eliminaciones',
    statusChanges: 'Cambios Estado',
    searchLog: 'Buscar en el log...',
    allModules: 'Todos los módulos',
    records: 'registros',
    noAuditLogs: 'No hay registros de auditoría todavía.',
    auditLogsDesc: 'Las acciones realizadas en el sistema aparecerán aquí automáticamente.',
    clearAuditLog: 'Limpiar Log de Auditoría',
    clearAuditLogConfirm: 'Esta acción eliminará permanentemente todos los registros de auditoría. ¿Estás seguro?',
    clearAll: 'Limpiar Todo',
    financesTitle: 'Gastos Empresa & Liquidación',
    summary: 'Resumen',
    registerExpense: 'Registrar Gasto',
    grossIncome: 'INGRESO BRUTO',
    grossIncomeDesc: 'Total pagado por clientes',
    provPayments: 'PROV. (PAGOS)',
    otaCommissions: 'OTA',
    otaDesc: 'Comisiones plataformas',
    drivers: 'CHOFERES',
    driversDesc: 'Pagos a conductores',
    operExpenses: 'GASTOS OPER.',
    operExpensesDesc: 'Incluye Nómina',
    realProfit: 'GANANCIA REAL',
    profitDesc: 'Ingresos - Gastos',
    provAndComm: 'Proveedores y Comisiones',
    driverLiq: 'Liquidación de Choferes',
    expenseLog: 'Bitácora de Gastos',
    selected: 'seleccionada(s)',
    pay: 'Pagar',
    print: 'Imprimir',
    date: 'FECHA',
    client: 'CLIENTE',
    provider: 'PROVEEDOR',
    baseCost: 'COSTO BASE',
    extras: 'EXTRAS',
    totalCost: 'COSTO TOTAL',
    clientPrice: 'PRECIO CL.',
    profit: 'GANANCIA',
    totals: 'TOTALES:',
    driver: 'CHOFER',
    service: 'SERVICIO',
    adults: 'ADULTOS',
    children: 'NIÑOS',
    amountCol: 'MONTO',
    category: 'CATEGORÍA',
    description: 'DESCRIPCIÓN',
    totalExpenses: 'TOTAL GASTOS:',
    periodSummary: 'RESUMEN DEL PERÍODO',
    totalBookingsLabel: 'Total Reservas:',
    grossIncomeLabel: 'Ingreso Bruto:',
    provPaymentLabel: 'Pago Proveedores:',
    otaCommLabel: 'Comisiones OTA:',
    driverPayLabel: 'Pagos Choferes:',
    operExpLabel: 'Gastos Operativos:',
    expBreakdown: 'Desglose Gastos:',
    gas: 'Gasolina:',
    maintenance: 'Mantenimiento:',
    guidePay: 'Pago Guías:',
    payroll: 'Pago Nómina:',
    others: 'Otros:',
    realProfitLabel: 'GANANCIA REAL:',
    expenseAmount: 'Monto US$',
    expenseDetail: 'Detalle',
    agenciesTitle: 'Gestión de Agencias',
    agenciesSubtitle: 'Directorio de agencias y comisiones.',
    newAgency: 'Nueva Agencia',
    editAgency: 'Editar Agencia',
    agencyName: 'Nombre de la Agencia',
    commission: 'Comisión (%)',
    searchAgency: 'Buscar agencia...',
    deleteAgencyTitle: '¿Eliminar Agencia?',
    driversTitle: 'Gestión de Choferes',
    driversSubtitle: 'Directorio de choferes y vehículos.',
    newDriver: 'Nuevo Chofer',
    editDriver: 'Editar Chofer',
    driverName: 'Nombre del Chofer',
    license: 'Licencia',
    vehicle: 'Vehículo',
    searchDriver: 'Buscar chofer...',
    deleteDriverTitle: '¿Eliminar Chofer?',
    providersTitle: 'Proveedores',
    providersSubtitle: 'Directorio de proveedores de actividades.',
    newProvider: 'Nuevo Proveedor',
    editProvider: 'Editar Proveedor',
    providerName: 'Nombre del Proveedor',
    contactPerson: 'Persona de Contacto',
    searchProvider: 'Buscar proveedor...',
    deleteProviderTitle: '¿Eliminar Proveedor?',
    activitiesTitle: 'Actividades Base',
    activitiesSubtitle: 'Actividades ofrecidas por proveedores.',
    newActivity: 'Nueva Actividad',
    editActivity: 'Editar Actividad',
    activityName: 'Nombre de Actividad',
    basePrice: 'Precio Base',
    searchActivity: 'Buscar actividad...',
    deleteActivityTitle: '¿Eliminar Actividad?',
    scheduleTitle: 'Horario',
    scheduleSubtitle: 'Calendario de actividades y traslados.',
    usersTitle: 'Gestión de Usuarios',
    usersSubtitle: 'Administración de accesos y roles del sistema.',
    newUser: 'Nuevo Usuario',
    editUser: 'Editar Usuario',
    userRole: 'Rol del Usuario',
    searchUser: 'Buscar usuario...',
    deleteUserTitle: '¿Eliminar Usuario?',
    userName: 'Nombre de Usuario',
    assignedBookings: 'Reservas Asignadas',
    driversDirectory: 'Directorio',
    pickupOrders: 'Órdenes',
    filter: 'Filtrar',
    dateCustomer: 'Fecha / Cliente',
    activity: 'Actividad',
    assignment: 'Asignación (Hora / Chofer / Pago)',
    contactWhatsapp: 'Contacto (WhatsApp)',
    viewPickupOrder: 'Ver Orden de Recogida',
    viewPickupSubtitle: 'Consulta las rutas asignadas a los choferes.',
    selectDriver: 'Seleccionar Chofer',
    dateFrom: 'Fecha Desde',
    dateTo: 'Fecha Hasta',
    generatePickupReport: 'Generar Reporte de Recogida',
    driverActive: 'Chofer Activo (disponible para asignaciones)',
    deleteDriverWarning: '¿Estás seguro que deseas eliminar este chofer? Esta acción no se puede deshacer y desvinculará sus asignaciones previas.',
    // Orders
    ordersTitle: 'Control de Órdenes',
    newOrder: 'Nueva Orden',
    editOrder: 'Editar Orden',
    orderCreated: 'Orden creada exitosamente',
    orderUpdated: 'Orden actualizada',
    ordersDeleted: 'órdenes eliminadas',
    printingOrders: 'Imprimiendo órdenes seleccionadas...',
    noOrdersMatch: 'No hay órdenes que coincidan con los filtros.',
    ref: 'Ref.',
    time: 'Hora',
    type: 'Tipo',
    route: 'Ruta',
    providerPrice: 'Precio Prov.',
    payment: 'Pago',
    deleteConfirmOrders: '¿Estás seguro de que deseas eliminar las',
    selectedOrders: 'órdenes seleccionadas?',
    pointRoute: 'Punto / Ruta',
    assignProvider: 'Asignar Proveedor',
    assignDriver: 'Asignar Chofer',
    none: 'Ninguno',
    saveOrder: 'Guardar Orden',
    clientName: 'Nombre cliente',
    // ProvidersActivities
    providersAndActivities: 'Proveedores y Actividades',
    providers: 'Proveedores',
    activities: 'Actividades',
    editProviderTitle: 'Editar Proveedor',
    newProviderTitle: 'Nuevo Proveedor',
    companyPersonName: 'Nombre Empresa / Persona',
    internalNotes: 'Notas internas',
    updateProvider: 'Actualizar Proveedor',
    createProvider: 'Crear Proveedor',
    providerList: 'Listado de Proveedores',
    name: 'Nombre',
    editActivityTitle: 'Editar Actividad',
    newActivityTitle: 'Nueva Actividad',
    baseCostField: 'Costo Base (US$)',
    chargeMode: 'Modo Cobro',
    perPerson: 'Por Persona (PAX)',
    perTrip: 'Por Viaje (TRIP)',
    activityAvailable: 'Actividad Disponible',
    commissionConfig: 'Configuración de Comisiones (Plataformas)',
    otherDirect: 'Otras / Directo',
    updateActivity: 'Actualizar Actividad',
    saveActivity: 'Guardar Actividad',
    activityList: 'Listado de Actividades',
    cost: 'Costo',
    noProviders: 'No hay proveedores registrados',
    unknown: 'Desconocido',
    providerSaved: 'Proveedor guardado',
    providerDeleted: 'Proveedor eliminado',
    activitySaved: 'Actividad guardada',
    activityDeleted: 'Actividad eliminada',
    today: 'Hoy',
    servicesThisWeek: 'Servicios esta semana',
    servicesTitle: 'SERVICIOS',
    user: 'Usuario',
    totalUsers: 'Total usuarios',
    admins: 'Administradores',
    ops: 'Operaciones',
    searchUsersPlaceholder: 'Buscar por nombre, email o rol…',
    noUsers: 'No hay usuarios',
    statusUpdated: 'Estado actualizado',
    userSaved: 'Usuario guardado',
    userDeleted: 'Usuario eliminado',
    passwordOptional: 'Nueva contraseña (opcional)',
    leaveBlank: 'Dejar en blanco para no cambiar',
    passwordRequired: 'Requerida',
    deleteUserMessage: 'Esta acción no se puede deshacer.',
    backupDownloaded: 'Copia de seguridad descargada exitosamente',
    importError: 'Error al importar. El archivo no es un respaldo válido.',
    dataMerged: 'Datos fusionados correctamente.',
    dataRestored: 'Datos restaurados correctamente.',
    processError: 'Error al procesar los datos.',
    settingsSubtitle: 'Personaliza la plataforma a tu medida',
    companyInfoDesc: 'Datos principales de tu empresa',
    accountDataDesc: 'Información de tu cuenta personal',
    appearanceDesc: 'Cambia la apariencia del panel',
    notifDesc: 'Controla qué alertas recibes y con qué frecuencia',
    securityDesc: 'Actualiza tu contraseña de acceso',
    activeSessionsDesc: 'Dispositivos con sesión activa',
    backupRecovery: 'Respaldo y Recuperación',
    backupRecoveryDesc: 'Protege tu información exportando tus datos periódicamente',
    exportData: 'Exportar Datos',
    exportDataDesc: 'Descarga un archivo JSON con todas tus reservas, clientes y configuraciones.',
    downloadCopy: 'Descargar Copia',
    importRestore: 'Importar / Restaurar',
    importRestoreDesc: 'Sube tu archivo JSON previamente descargado para restaurar el sistema.',
    uploadJson: 'Subir Archivo JSON',
    importData: 'Importar Datos',
    importDataPrompt: 'Has seleccionado un archivo de respaldo. ¿Cómo deseas proceder con la información?',
    mergeData: 'Fusionar Datos (Seguro)',
    mergeDataDesc: 'Agrega la información nueva del archivo sin borrar lo que ya tienes.',
    replaceData: 'Reemplazar Todo (Peligroso)',
    replaceDataDesc: 'Borra todos tus datos actuales y deja el sistema exactamente como está en el archivo.',
    instant: 'Inmediato',
    hourly: 'Cada hora',
    daily: 'Diario',
    weekly: 'Semanal',
    sun: 'Dom',
    mon: 'Lun',
    tue: 'Mar',
    wed: 'Mié',
    thu: 'Jue',
    fri: 'Vie',
    sat: 'Sáb',
    serv: 'serv.',
    ordersCount: 'órdenes',
    selectedCount: 'seleccionadas',
    newOrderFor: 'Nueva orden para',
    orderUpdated: 'Orden actualizada',
    orderCreated: 'Orden creada',
    ordersDeleted: 'órdenes eliminadas',
    allProviders: 'Todos los proveedores',
    allDrivers: 'Todos los choferes',
    searchClient: 'Buscar cliente…',
    ref: 'Ref',
    route: 'Ruta',
    pax: 'Pax',
    price: 'Precio',
    payment: 'Pago',
    noOrdersFilters: 'No hay órdenes con esos filtros',
    adults: 'Adultos',
    children: 'Niños',
    providerPrice: 'Precio proveedor',
    none: '— Ninguno —',
    deleteOrdersTitle: '¿Eliminar órdenes?',
    deleteOrdersMsg: 'Vas a eliminar {count} órdenes. Esta acción no se puede deshacer.',
    date: 'Fecha',
    time: 'Hora',
    type: 'Tipo',
    client: 'Cliente',
    service: 'Servicio',
    auditSubtitle: 'Registro completo de acciones del sistema',
    totalEvents: 'Total eventos',
    eventsToday: 'Eventos hoy',
    createsToday: 'Creaciones hoy',
    modules: 'Módulos',
    searchAudit: 'Buscar en auditoría…',
    allModulesFilter: 'Todos los módulos',
    module: 'Módulo',
    action: 'Acción',
    detail: 'Detalle',
    dateTime: 'Fecha y hora',
    noAuditEvents: 'No hay eventos de auditoría',
    adminPanel: 'Panel administrativo de ingresos y egresos',
    summary: 'Resumen del período',
    registerExpense: 'Registrar Gasto',
    grossIncome: 'Ingresos Brutos',
    grossIncomeDesc: 'Total de todas las reservas',
    provPayments: 'Pago a Proveedores',
    otaCommissions: 'Comisiones OTA',
    otaDesc: 'Lo que retiene Expedia, TripAdvisor, etc.',
    driversDesc: 'Traslados pagados a choferes',
    operExpenses: 'Gastos Operativos',
    operExpensesDesc: 'Gasolina, mantenimiento, nómina, etc.',
    realProfit: 'Ganancia Real',
    profitDesc: 'Ingresos Brutos menos todos los egresos',
    driverFilterPlaceholder: '-- Chofer --',
    providerFilterPlaceholder: '-- Proveedor --',
    categoryFilterPlaceholder: '-- Categoría --',
    searchClientPlaceholder: 'Buscar cliente...',
    clear: 'Limpiar',
    provAndComm: 'Prov. y Comisiones',
    driverLiq: 'Liquidación Choferes',
    expenseLog: 'Historial Gastos',
    pay: 'Pagar',
    baseCost: 'Costo Base',
    extras: 'Extras',
    totalCost: 'Costo Total',
    clientPrice: 'Precio Cliente',
    profit: 'Ganancia',
    status: 'Estado',
    totals: 'TOTALES',
    totalDrivers: 'TOTAL CHOFERES:',
    amountCol: 'Monto',
    selectedFem: 'seleccionada(s)',
    category: 'Categoría',
    description: 'Descripción',
    totalExpenses: 'TOTAL GASTOS:',
    periodSummary: 'Resumen del Período',
    totalBookingsLabel: 'Total Reservas:',
    grossIncomeLabel: 'Ingresos Brutos:',
    provPaymentLabel: 'Pago a Proveedores:',
    otaCommLabel: 'Comisiones OTA:',
    driverPayLabel: 'Pago a Choferes:',
    operExpLabel: 'Gastos Operativos:',
    expBreakdown: 'Desglose de Gastos',
    gas: 'Gasolina',
    maintenance: 'Mantenimiento',
    guidePay: 'Pago Guías',
    payroll: 'Pago Nómina',
    others: 'Otros',
    realProfitLabel: 'Ganancia Real:',
    expenseAmount: 'Monto del Gasto',
    expenseDetail: 'Detalle del gasto',
    deleteExpenses: 'Eliminar Gastos',
    deleteExpensesConfirm: '¿Estás seguro de que deseas eliminar {count} gasto(s)? Esta acción no se puede deshacer.',
    searchPlaceholder: 'Buscar reservas, tours, clientes…',
    lightModeTooltip: 'Modo claro',
    darkModeTooltip: 'Modo oscuro',
    openMenu: 'Abrir menú',
    closeSidebar: 'Cerrar sidebar',
    collapseSidebar: 'Colapsar sidebar',
    collapseSidebar: 'Colapsar sidebar',
    userDefault: 'Usuario',
    dashboardSubtitle: 'Resumen de operaciones — Punta Cana, RD',
    week: 'Semana',
    month: 'Mes',
    year: 'Año',
    totalBookings: 'Total Reservas',
    revenue: 'Ingresos',
    completedToday: 'Completados Hoy',
    vsLastWeek: 'vs semana pasada',
    vsYesterday: 'vs ayer',
    bookingsThisWeek: 'Reservas esta semana',
    viewAll: 'Ver todos',
    topTours: 'Tours más reservados',
    noDataYet: 'Sin datos aún',
    upcomingBookings: 'Próximas reservas',
    noUpcomingBookings: 'No hay reservas próximas',
    operationalHealth: 'Estado operativo',
    periodExpenses: 'Gastos del periodo',
    filtered: 'filtradas',
    filters: 'Filtros',
    activityType: 'Actividad',
    transferType: 'Traslado',
    noBookings: 'No se encontraron reservas.',
    roundTrip: 'Viaje ida y vuelta',
    returnDate: 'Fecha de regreso',
    returnTime: 'Hora de regreso',
    paymentDone: 'Pago realizado',
    platformPercent: 'Porcentaje plataforma',
    driverPayment: 'Pago al chofer',
    dropoff: 'Punto de destino',
    flight: 'Vuelo',
    bookingSingular: 'reserva',
    bookingsPlural: 'reservas',
    type: 'Tipo',
    actividad: 'Actividad',
    traslado: 'Traslado',
    confirmado: 'Confirmado',
    completado: 'Completado',
    platform: 'Plataforma',
    providerCost: 'Costo Proveedor',
    activitiesTitle: 'Actividades y Excursiones',
    activitiesSubtitle: 'Catálogo centralizado de servicios ofrecidos.',
    newService: 'Nuevo Servicio',
    searchService: 'Buscar servicio por nombre, proveedor o categoría...',
    adminView: 'Vista Administrativa (Tabla)',
    clientView: 'Vista de Cliente (Catálogo)',
    serviceProvider: 'Servicio / Proveedor',
    baseCost: 'Costo base',
    commissions: 'Comisiones',
    finalPrice: 'Precio final',
    noServices: 'No hay servicios registrados',
    noResults: 'No hay resultados',
    tryOtherTerms: 'Prueba buscando con otros términos.',
    editService: 'Editar Servicio',
    serviceName: 'Nombre del Servicio',
    categoryActivity: 'Actividad (General)',
    categoryExcursion: 'Excursión (Tour)',
    categoryTransfer: 'Traslado',
    categoryPark: 'Parque Temático',
    providerResponsible: 'Proveedor Responsable',
    baseCostUsd: 'Costo Base Proveedor (US$)',
    chargeMode: 'Modo de cobro (Base)',
    perPerson: 'Por persona (pax)',
    perVehicle: 'Por vehículo',
    imageUrlOpt: 'URL de Imagen (Opcional)',
    serviceActive: 'Servicio Disponible (Activo)',
    descDetails: 'Descripción y Detalles (Qué incluye)',
    otaCommissionsTitle: 'Comisiones a Plataformas de Venta (OTA)',
    commissionPercent: 'Comisión (%)',
    notConfigured: 'No configurado',
    dynamicPrice: 'Precio Venta Dinámico:',
    dynamicPriceDesc: '(Basado en costo + comisiones)',
    createService: 'Crear Servicio',
    saveChanges: 'Guardar Cambios',
    deleteServiceTitle: '¿Eliminar servicio?',
    deleteServiceText: 'Esta acción no se puede deshacer y puede afectar registros históricos.',
    agenciesTitle: 'Agencias',
    agenciesSubtitle: 'Gestión de agencias colaboradoras',
    newAgency: 'Nueva Agencia',
    searchAgency: 'Buscar agencia...',
    agencyName: 'Nombre de la agencia',
    noAgencies: 'No hay agencias registradas',
    editAgency: 'Editar Agencia',
    update: 'Actualizar',
    create: 'Crear',
    deleteAgencyTitle: '¿Eliminar agencia?',
    deleteAgencyText: 'Esta acción no se puede deshacer.',
    name: 'Nombre',
    driversTitle: 'Choferes y Asignaciones',
    driversSubtitle: 'Gestión de flota y rutas de recogida',
    newDriver: 'Nuevo Chofer',
    assignServices: 'Asignar servicios',
    directory: 'Directorio',
    pickupOrders: 'Órdenes de recogida',
    pendingAssignments: 'Reservas pendientes de asignar',
    allActivities: 'Todas las actividades',
    driver: 'Chofer',
    vehicle: 'Vehículo',
    noServicesInRange: 'No hay servicios en este rango',
    noDriver: 'Sin chofer',
    assign: 'Asignar',
    driversDirectory: 'Directorio de choferes',
    contact: 'Contacto',
    noDrivers: 'No hay choferes registrados',
    active: 'Activo',
    inactive: 'Inactivo',
    printRoutesDesc: 'Consulta las rutas asignadas a los choferes para imprimir.',
    from: 'Desde',
    to: 'Hasta',
    print: 'Imprimir',
    hotelRoute: 'Hotel / Ruta',
    service: 'Servicio',
    noBookingsFound: 'No se encontraron reservas con esos filtros',
    editDriver: 'Editar Chofer',
    driverName: 'Nombre del chofer',
    whatsappPhone: 'WhatsApp / Teléfono',
    driverActive: 'Chofer activo (disponible para asignaciones)',
    assignDriver: 'Asignar chofer',
    pickupTime: 'Hora de recogida',
    driverPaymentUsd: 'Pago chofer (US$)',
    saveAssignment: 'Guardar asignación',
    deleteDriverTitle: '¿Eliminar chofer?',
    deleteDriverText: 'Esta acción no se puede deshacer y desvinculará sus asignaciones.',
    welcome: 'Bienvenido',
    welcomeBack: 'Bienvenido de vuelta',
    enterCredentials: 'Ingresa tus credenciales para acceder al panel.',
    entering: 'Ingresando',
    enterPanel: 'Ingresar al panel',
    loginError: 'Credenciales inválidas.',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Reservas',
    moduleOrders: 'Órdenes',
    moduleSchedule: 'Agenda',
    moduleActivities: 'Actividades',
    moduleCustomers: 'Clientes',
    moduleDrivers: 'Choferes',
    moduleProviders: 'Proveedores',
    moduleAgencies: 'Agencias',
    moduleFinances: 'Finanzas',
    moduleAudit: 'Auditoría',
    moduleUsers: 'Usuarios',
    moduleSettings: 'Ajustes',
    notifWelcome: '🎉 Bienvenido a Jhoraji Tours. Tu panel está listo.',
    notifFinance: '📊 Reporte financiero del mes disponible en Finanzas.',
    notifSchedule: '📅 Tienes {count} reservas programadas para hoy.',
    notifScheduleItems: '📅 {count} servicio(s) programados para hoy.',
    notifDriver: '🚗 Chofer "{name}" asignado a traslado aeropuerto.',
    notifCustomer: '👤 Nuevo cliente registrado: {name}.',
    notifCustomerBase: '👤 Tu base de clientes tiene {count} registro(s).',
    notifPaymentDone: '✅ Reserva #{ref} marcada como pagada.',
    notifPendingPayments: '💳 Tienes {count} reservas pendientes de pago.',
    notifTour: '🏝️ Tour "{name}" activado en la web.',
    notifNewOrder: '📦 Nueva orden para {client}.',
    notifNewCustomerManual: '👤 Nuevo cliente: {name}.',
    notifNewBooking: '📅 Nueva reserva: {ref}.',
  },
  en: {
    modulesSection: 'MODULES',
    managementSection: 'MANAGEMENT',
    adminSection: 'ADMINISTRATION',
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    tours: 'Tours',
    customers: 'Customers',
    settings: 'Settings',
    logout: 'Log Out',
    notificaciones: 'Notifications',
    marcarLeidas: 'Mark as read',
    limpiar: 'Clear',
    sinNotificaciones: 'No notifications.',
    reservasTitle: 'Booking Management',
    settingsTitle: 'System Settings',
    dashboardTitle: 'General Overview',
    adminPanel: 'Admin panel',
    notifications: 'Notifications',
    seeAll: 'See all',
    myProfile: 'My Profile',
    general: 'General',
    appearance: 'Appearance',
    security: 'Security',
    profile: 'Profile',
    search: 'Search',
    actions: 'Actions',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    create: 'Create',
    update: 'Update',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    paid: 'Paid',
    pending: 'Pending',
    canceled: 'Canceled',
    new: 'New',
    vip: 'VIP',
    status: 'Status',
    customer: 'Customer',
    customersTitle: 'Customer Management',
    customersSubtitle: 'Customer directory and booking history.',
    newCustomer: 'New Customer',
    editCustomer: 'Edit Customer',
    customerProfile: 'Customer Profile',
    customerSaved: 'Customer saved successfully',
    customerDeleted: 'Customer deleted',
    fullName: 'Full name',
    contact: 'Contact',
    country: 'Country',
    countryOrigin: 'Country of origin',
    totalBookings: 'Total bookings',
    totalSpent: 'Total spent',
    lastVisit: 'Last visit',
    searchCustomers: 'Search by name, email or country...',
    deleteCustomerTitle: 'Delete Customer?',
    deleteCustomerText: 'This action will remove the selected customer. Are you sure?',
    bookingsTitle: 'Booking Management',
    bookingsSubtitle: 'Manage all accounting system bookings.',
    newBooking: 'New Booking',
    editBooking: 'Edit Booking',
    bookingDetail: 'Booking Detail',
    bookingSaved: 'Booking saved successfully',
    bookingDeleted: 'Booking deleted',
    searchBookings: 'Search bookings...',
    bookingId: 'ID',
    tour: 'Tour',
    date: 'Date',
    pax: 'Pax',
    people: 'People',
    hotel: 'Hotel',
    amount: 'Amount',
    totalAmount: 'Total amount',
    notes: 'Notes',
    noNotes: 'No additional notes.',
    customerName: 'Customer Name',
    paymentStatus: 'Payment Status',
    pickup: 'Hotel / Pickup',
    saveBooking: 'Save Booking',
    deleteBookingTitle: 'Delete Booking?',
    deleteBookingText: 'This action cannot be undone. Are you sure you want to delete booking',
    toursTitle: 'Tour Management',
    toursSubtitle: 'Add, edit or disable tours available on the website.',
    newTour: 'New Tour',
    editTour: 'Edit Tour',
    tourSaved: 'Tour saved successfully',
    tourDeleted: 'Tour deleted successfully',
    tourStatusUpdated: 'Tour status updated',
    searchTours: 'Search tour...',
    category: 'Category',
    duration: 'Duration',
    rating: 'Rating',
    adultPrice: 'Adult Price',
    childPrice: 'Child Price',
    imageUrl: 'Image URL',
    description: 'Description',
    includes: 'Includes',
    title: 'Title',
    island: 'Island',
    adventure: 'Adventure',
    culture: 'Culture',
    nature: 'Nature',
    halfDay: 'Half Day',
    fullDay: 'Full Day',
    deleteTourTitle: 'Delete Tour?',
    deleteTourText: 'This action cannot be undone. It will be hidden from the website.',
    systemPreferences: 'Manage system preferences and your account.',
    companyInfo: 'Company Information',
    companyName: 'Company Name',
    email: 'Email Address',
    phone: 'Phone Number',
    website: 'Website',
    currency: 'Main Currency',
    saveChanges: 'Save Changes',
    visualCustomization: 'Visual Customization',
    systemTheme: 'System Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    darkModeDesc: 'Change the panel appearance to dark colors.',
    primaryColor: 'Primary Color',
    panelLanguage: 'Panel Language',
    panelLanguageDesc: 'Choose the interface language of the system.',
    spanish: 'Spanish',
    english: 'English',
    notifPreferences: 'Notification Preferences',
    accountSecurity: 'Account Security',
    activeSessions: 'Active Sessions',
    currentSession: 'Current',
    closeSession: 'Close Session',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated successfully',
    passwordsDontMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    currentPasswordRequired: 'Enter the current password',
    preferenceUpdated: 'Preference updated',
    colorUpdated: 'Color updated',
    changesSaved: 'Changes saved',
    sessionClosed: 'Session closed',
    role: 'Role',
    department: 'Department',
    lastAccess: 'Last access',
    accessLevel: 'Access level',
    accountData: 'Account details',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Receive a daily email with the bookings summary.',
    newBookingAlerts: 'New Booking Alerts',
    newBookingAlertsDesc: 'Instant notification when a customer makes a booking.',
    paymentAlerts: 'Payment Alerts',
    paymentAlertsDesc: 'Alerts when a card payment is confirmed.',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Browser notifications.',
    browserPermissionGranted: 'Notification permission enabled',
    browserPermissionDenied: 'The browser did not allow notifications',
    browserPermissionUnsupported: 'This browser does not support push notifications',
    dashboardSummary: 'Dashboard Summary',
    dashboardWelcome: 'Welcome back, here is the status of Jhoraji Tours.',
    downloadReport: 'Download Report',
    reportGenerated: 'Report generated successfully',
    totalRevenue: 'Total Revenue',
    todayBookings: 'Bookings Today',
    newCustomers: 'New Customers',
    activeTours: 'Active Tours',
    thisMonth: 'this month',
    recentBookings: 'Recent Bookings',
    popularTours: 'Popular Tours',
    loginSubtitle: 'Booking and Accounting System',
    password: 'Password',
    rememberMe: 'Remember me',
    login: 'Log In',
    loginSuccess: 'Login successful',
    loginError: 'Incorrect email or password. Please try again.',
    forgotCredentials: 'Forgot your credentials?',
    contactSupport: 'Contact technical support',
    usdCurrency: 'USD - US Dollar',
    eurCurrency: 'EUR - Euro',
    dopCurrency: 'DOP - Dominican Peso',
    sales: 'sales',
    noCustomersFound: 'No customers found.',
    permissions: 'Permissions',
    permissionsDesc: 'Manage access to modules based on role.',
    selectCountry: 'Select a country',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Bookings',
    moduleTours: 'Tours',
    moduleCustomers: 'Customers',
    moduleSettings: 'Settings',
    moduleUsers: 'Users',
    moduleDrivers: 'Drivers',
    moduleProviders: 'Providers',
    moduleAgencies: 'Agencies',
    moduleActivities: 'Activities',
    moduleSchedule: 'Schedule',
    moduleFinances: 'Finances',
    moduleAudit: 'Audit',
    moduleOrders: 'Orders',
    roleOperator: 'Booking Operator',
    roleAgent: 'Sales Agent',
    moduleAccess: 'Module Access',
    actionPermissions: 'Action Permissions',
    actionCreate: 'Create records',
    actionEdit: 'Edit records',
    actionDelete: 'Delete records',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    auditTitle: 'System Audit',
    auditSubtitle: 'Log of all actions performed in the system',
    update: 'Refresh',
    clearLog: 'Clear Log',
    totalActions: 'Total Actions',
    creations: 'Creations',
    editions: 'Edits',
    deletions: 'Deletions',
    statusChanges: 'Status Changes',
    searchLog: 'Search log...',
    allModules: 'All modules',
    records: 'records',
    noAuditLogs: 'No audit logs yet.',
    auditLogsDesc: 'Actions performed in the system will appear here automatically.',
    clearAuditLog: 'Clear Audit Log',
    clearAuditLogConfirm: 'This action will permanently delete all audit logs. Are you sure?',
    clearAll: 'Clear All',
    financesTitle: 'Company Expenses & Settlement',
    summary: 'Summary',
    registerExpense: 'Register Expense',
    grossIncome: 'GROSS INCOME',
    grossIncomeDesc: 'Total paid by customers',
    provPayments: 'PROV. (PAYMENTS)',
    otaCommissions: 'OTA',
    otaDesc: 'Platform commissions',
    drivers: 'DRIVERS',
    driversDesc: 'Driver payments',
    operExpenses: 'OPER. EXPENSES',
    operExpensesDesc: 'Includes Payroll',
    realProfit: 'REAL PROFIT',
    profitDesc: 'Income - Expenses',
    provAndComm: 'Providers and Commissions',
    driverLiq: 'Driver Settlement',
    expenseLog: 'Expense Log',
    selected: 'selected',
    pay: 'Pay',
    print: 'Print',
    date: 'DATE',
    client: 'CLIENT',
    provider: 'PROVIDER',
    baseCost: 'BASE COST',
    extras: 'EXTRAS',
    totalCost: 'TOTAL COST',
    clientPrice: 'CL. PRICE',
    profit: 'PROFIT',
    totals: 'TOTALS:',
    driver: 'DRIVER',
    service: 'SERVICE',
    adults: 'ADULTS',
    children: 'CHILDREN',
    amountCol: 'AMOUNT',
    category: 'CATEGORY',
    description: 'DESCRIPTION',
    totalExpenses: 'TOTAL EXPENSES:',
    periodSummary: 'PERIOD SUMMARY',
    totalBookingsLabel: 'Total Bookings:',
    grossIncomeLabel: 'Gross Income:',
    provPaymentLabel: 'Provider Payment:',
    otaCommLabel: 'OTA Commissions:',
    driverPayLabel: 'Driver Payments:',
    operExpLabel: 'Operating Expenses:',
    expBreakdown: 'Expense Breakdown:',
    gas: 'Gas:',
    maintenance: 'Maintenance:',
    guidePay: 'Guide Pay:',
    payroll: 'Payroll:',
    others: 'Others:',
    realProfitLabel: 'REAL PROFIT:',
    expenseAmount: 'Amount',
    expenseDetail: 'Detail',
    agenciesTitle: 'Agencies Management',
    agenciesSubtitle: 'Directory of agencies and commissions.',
    newAgency: 'New Agency',
    editAgency: 'Edit Agency',
    agencyName: 'Agency Name',
    commission: 'Commission (%)',
    searchAgency: 'Search agency...',
    deleteAgencyTitle: 'Delete Agency?',
    driversTitle: 'Drivers Management',
    driversSubtitle: 'Directory of drivers and vehicles.',
    newDriver: 'New Driver',
    editDriver: 'Edit Driver',
    driverName: 'Driver Name',
    license: 'License',
    vehicle: 'Vehicle',
    searchDriver: 'Search driver...',
    deleteDriverTitle: 'Delete Driver?',
    providersTitle: 'Providers',
    providersSubtitle: 'Directory of activity providers.',
    newProvider: 'New Provider',
    editProvider: 'Edit Provider',
    providerName: 'Provider Name',
    contactPerson: 'Contact Person',
    searchProvider: 'Search provider...',
    deleteProviderTitle: 'Delete Provider?',
    activitiesTitle: 'Base Activities',
    activitiesSubtitle: 'Activities offered by providers.',
    newActivity: 'New Activity',
    editActivity: 'Edit Activity',
    activityName: 'Activity Name',
    basePrice: 'Base Price',
    searchActivity: 'Search activity...',
    deleteActivityTitle: 'Delete Activity?',
    scheduleTitle: 'Schedule',
    scheduleSubtitle: 'Calendar of activities and transfers.',
    usersTitle: 'Users Management',
    usersSubtitle: 'Management of system access and roles.',
    newUser: 'New User',
    editUser: 'Edit User',
    userRole: 'User Role',
    searchUser: 'Search user...',
    deleteUserTitle: 'Delete User?',
    userName: 'User Name',
    assignedBookings: 'Assigned Bookings',
    driversDirectory: 'Directory',
    pickupOrders: 'Orders',
    filter: 'Filter',
    dateCustomer: 'Date / Customer',
    activity: 'Activity',
    assignment: 'Assignment (Time / Driver / Payment)',
    contactWhatsapp: 'Contact (WhatsApp)',
    viewPickupOrder: 'View Pickup Order',
    viewPickupSubtitle: 'Check the routes assigned to drivers.',
    selectDriver: 'Select Driver',
    dateFrom: 'Date From',
    dateTo: 'Date To',
    generatePickupReport: 'Generate Pickup Report',
    driverActive: 'Active Driver (available for assignments)',
    deleteDriverWarning: 'Are you sure you want to delete this driver? This action cannot be undone and will unlink previous assignments.',
    // Orders
    ordersTitle: 'Order Control',
    newOrder: 'New Order',
    editOrder: 'Edit Order',
    orderCreated: 'Order created successfully',
    orderUpdated: 'Order updated',
    ordersDeleted: 'orders deleted',
    printingOrders: 'Printing selected orders...',
    noOrdersMatch: 'No orders match the filters.',
    ref: 'Ref.',
    time: 'Time',
    type: 'Type',
    route: 'Route',
    providerPrice: 'Prov. Price',
    payment: 'Payment',
    deleteConfirmOrders: 'Are you sure you want to delete the',
    selectedOrders: 'selected orders?',
    pointRoute: 'Point / Route',
    assignProvider: 'Assign Provider',
    assignDriver: 'Assign Driver',
    none: 'None',
    saveOrder: 'Save Order',
    clientName: 'Customer name',
    // ProvidersActivities
    providersAndActivities: 'Providers and Activities',
    providers: 'Providers',
    activities: 'Activities',
    editProviderTitle: 'Edit Provider',
    newProviderTitle: 'New Provider',
    companyPersonName: 'Company / Person Name',
    internalNotes: 'Internal notes',
    updateProvider: 'Update Provider',
    createProvider: 'Create Provider',
    providerList: 'Provider List',
    name: 'Name',
    editActivityTitle: 'Edit Activity',
    newActivityTitle: 'New Activity',
    baseCostField: 'Base Cost (US$)',
    chargeMode: 'Charge Mode',
    perPerson: 'Per Person (PAX)',
    perTrip: 'Per Trip (TRIP)',
    activityAvailable: 'Activity Available',
    commissionConfig: 'Commission Configuration (Platforms)',
    otherDirect: 'Other / Direct',
    updateActivity: 'Update Activity',
    saveActivity: 'Save Activity',
    activityList: 'Activity List',
    cost: 'Cost',
    noProviders: 'No providers registered',
    unknown: 'Unknown',
    providerSaved: 'Provider saved',
    providerDeleted: 'Provider deleted',
    activitySaved: 'Activity saved',
    activityDeleted: 'Activity deleted',
    today: 'Today',
    servicesThisWeek: 'Services this week',
    servicesTitle: 'SERVICES',
    user: 'User',
    totalUsers: 'Total users',
    admins: 'Administrators',
    ops: 'Operations',
    searchUsersPlaceholder: 'Search by name, email or role…',
    noUsers: 'No users found',
    statusUpdated: 'Status updated',
    userSaved: 'User saved',
    userDeleted: 'User deleted',
    passwordOptional: 'New password (optional)',
    leaveBlank: 'Leave blank to keep current',
    passwordRequired: 'Required',
    deleteUserMessage: 'This action cannot be undone.',
    backupDownloaded: 'Backup downloaded successfully',
    importError: 'Import error. The file is not a valid backup.',
    dataMerged: 'Data merged successfully.',
    dataRestored: 'Data restored successfully.',
    processError: 'Error processing data.',
    settingsSubtitle: 'Customize the platform to your needs',
    companyInfoDesc: 'Main details of your company',
    accountDataDesc: 'Your personal account information',
    appearanceDesc: 'Change the panel appearance',
    notifDesc: 'Control which alerts you receive and how often',
    securityDesc: 'Update your access password',
    activeSessionsDesc: 'Devices with active sessions',
    backupRecovery: 'Backup and Recovery',
    backupRecoveryDesc: 'Protect your information by exporting your data periodically',
    exportData: 'Export Data',
    exportDataDesc: 'Download a JSON file with all your bookings, customers and settings.',
    downloadCopy: 'Download Copy',
    importRestore: 'Import / Restore',
    importRestoreDesc: 'Upload your previously downloaded JSON file to restore the system.',
    uploadJson: 'Upload JSON File',
    importData: 'Import Data',
    importDataPrompt: 'You have selected a backup file. How do you wish to proceed with the information?',
    mergeData: 'Merge Data (Safe)',
    mergeDataDesc: 'Adds the new information from the file without deleting what you already have.',
    replaceData: 'Replace All (Dangerous)',
    replaceDataDesc: 'Deletes all your current data and leaves the system exactly as it is in the file.',
    instant: 'Instant',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    serv: 'srv.',
    ordersCount: 'orders',
    selectedCount: 'selected',
    newOrderFor: 'New order for',
    orderUpdated: 'Order updated',
    orderCreated: 'Order created',
    ordersDeleted: 'orders deleted',
    allProviders: 'All providers',
    allDrivers: 'All drivers',
    searchClient: 'Search client…',
    ref: 'Ref',
    route: 'Route',
    pax: 'Pax',
    price: 'Price',
    payment: 'Payment',
    noOrdersFilters: 'No orders found with these filters',
    adults: 'Adults',
    children: 'Children',
    providerPrice: 'Provider price',
    none: '— None —',
    deleteOrdersTitle: 'Delete orders?',
    deleteOrdersMsg: 'You are going to delete {count} orders. This action cannot be undone.',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    client: 'Client',
    service: 'Service',
    auditSubtitle: 'Complete system actions log',
    totalEvents: 'Total events',
    eventsToday: 'Events today',
    createsToday: 'Creates today',
    modules: 'Modules',
    searchAudit: 'Search audit…',
    allModulesFilter: 'All modules',
    module: 'Module',
    action: 'Action',
    detail: 'Detail',
    dateTime: 'Date and time',
    noAuditEvents: 'No audit events found',
    adminPanel: 'Administrative income and expenses panel',
    summary: 'Period summary',
    registerExpense: 'Register Expense',
    grossIncome: 'Gross Income',
    grossIncomeDesc: 'Total of all bookings',
    provPayments: 'Provider Payments',
    otaCommissions: 'OTA Commissions',
    otaDesc: 'Retained by Expedia, TripAdvisor, etc.',
    driversDesc: 'Transfers paid to drivers',
    operExpenses: 'Operating Expenses',
    operExpensesDesc: 'Gas, maintenance, payroll, etc.',
    realProfit: 'Real Profit',
    profitDesc: 'Gross Income minus all expenses',
    driverFilterPlaceholder: '-- Driver --',
    providerFilterPlaceholder: '-- Provider --',
    categoryFilterPlaceholder: '-- Category --',
    searchClientPlaceholder: 'Search client...',
    clear: 'Clear',
    provAndComm: 'Prov. and Commissions',
    driverLiq: 'Driver Liquidation',
    expenseLog: 'Expense Log',
    pay: 'Pay',
    baseCost: 'Base Cost',
    extras: 'Extras',
    totalCost: 'Total Cost',
    clientPrice: 'Client Price',
    profit: 'Profit',
    status: 'Status',
    totals: 'TOTALS',
    totalDrivers: 'TOTAL DRIVERS:',
    amountCol: 'Amount',
    selectedFem: 'selected',
    category: 'Category',
    description: 'Description',
    totalExpenses: 'TOTAL EXPENSES:',
    periodSummary: 'Period Summary',
    totalBookingsLabel: 'Total Bookings:',
    grossIncomeLabel: 'Gross Income:',
    provPaymentLabel: 'Provider Payments:',
    otaCommLabel: 'OTA Commissions:',
    driverPayLabel: 'Driver Payments:',
    operExpLabel: 'Operating Expenses:',
    expBreakdown: 'Expenses Breakdown',
    gas: 'Gas',
    maintenance: 'Maintenance',
    guidePay: 'Guide Pay',
    payroll: 'Payroll',
    others: 'Others',
    realProfitLabel: 'Real Profit:',
    expenseAmount: 'Expense Amount',
    expenseDetail: 'Expense detail',
    deleteExpenses: 'Delete Expenses',
    deleteExpensesConfirm: 'Are you sure you want to delete {count} expense(s)? This action cannot be undone.',
    searchPlaceholder: 'Search bookings, tours, clients…',
    lightModeTooltip: 'Light mode',
    darkModeTooltip: 'Dark mode',
    openMenu: 'Open menu',
    closeSidebar: 'Close sidebar',
    collapseSidebar: 'Collapse sidebar',
    collapseSidebar: 'Collapse sidebar',
    userDefault: 'User',
    dashboardSubtitle: 'Operations overview — Punta Cana, DR',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    totalBookings: 'Total Bookings',
    revenue: 'Revenue',
    completedToday: 'Completed Today',
    vsLastWeek: 'vs last week',
    vsYesterday: 'vs yesterday',
    bookingsThisWeek: 'Bookings this week',
    viewAll: 'View all',
    topTours: 'Top tours',
    noDataYet: 'No data yet',
    upcomingBookings: 'Upcoming bookings',
    noUpcomingBookings: 'No upcoming bookings',
    operationalHealth: 'Operational health',
    periodExpenses: 'Period expenses',
    filtered: 'filtered',
    filters: 'Filters',
    activityType: 'Activity',
    transferType: 'Transfer',
    noBookings: 'No bookings found.',
    roundTrip: 'Round trip',
    returnDate: 'Return date',
    returnTime: 'Return time',
    paymentDone: 'Payment done',
    platformPercent: 'Platform percentage',
    driverPayment: 'Driver payment',
    dropoff: 'Dropoff location',
    flight: 'Flight',
    bookingSingular: 'booking',
    bookingsPlural: 'bookings',
    type: 'Type',
    actividad: 'Activity',
    traslado: 'Transfer',
    confirmado: 'Confirmed',
    completado: 'Completed',
    platform: 'Platform',
    providerCost: 'Provider Cost',
    activitiesTitle: 'Activities and Tours',
    activitiesSubtitle: 'Centralized catalog of offered services.',
    newService: 'New Service',
    searchService: 'Search service by name, provider or category...',
    adminView: 'Administrative View (Table)',
    clientView: 'Client View (Catalog)',
    serviceProvider: 'Service / Provider',
    baseCost: 'Base cost',
    commissions: 'Commissions',
    finalPrice: 'Final price',
    noServices: 'No registered services',
    noResults: 'No results found',
    tryOtherTerms: 'Try searching with other terms.',
    editService: 'Edit Service',
    serviceName: 'Service Name',
    categoryActivity: 'Activity (General)',
    categoryExcursion: 'Excursion (Tour)',
    categoryTransfer: 'Transfer',
    categoryPark: 'Theme Park',
    providerResponsible: 'Responsible Provider',
    baseCostUsd: 'Provider Base Cost (US$)',
    chargeMode: 'Charge Mode (Base)',
    perPerson: 'Per person (pax)',
    perVehicle: 'Per vehicle',
    imageUrlOpt: 'Image URL (Optional)',
    serviceActive: 'Service Available (Active)',
    descDetails: 'Description and Details (What is included)',
    otaCommissionsTitle: 'Sales Platforms Commissions (OTA)',
    commissionPercent: 'Commission (%)',
    notConfigured: 'Not configured',
    dynamicPrice: 'Dynamic Sale Price:',
    dynamicPriceDesc: '(Based on cost + commissions)',
    createService: 'Create Service',
    saveChanges: 'Save Changes',
    deleteServiceTitle: 'Delete service?',
    deleteServiceText: 'This action cannot be undone and may affect historical records.',
    agenciesTitle: 'Agencies',
    agenciesSubtitle: 'Management of collaborating agencies',
    newAgency: 'New Agency',
    searchAgency: 'Search agency...',
    agencyName: 'Agency name',
    noAgencies: 'No registered agencies',
    editAgency: 'Edit Agency',
    update: 'Update',
    create: 'Create',
    deleteAgencyTitle: 'Delete agency?',
    deleteAgencyText: 'This action cannot be undone.',
    name: 'Name',
    driversTitle: 'Drivers and Assignments',
    driversSubtitle: 'Fleet and pickup routes management',
    newDriver: 'New Driver',
    assignServices: 'Assign services',
    directory: 'Directory',
    pickupOrders: 'Pickup orders',
    pendingAssignments: 'Pending assignments',
    allActivities: 'All activities',
    driver: 'Driver',
    vehicle: 'Vehicle',
    noServicesInRange: 'No services in this range',
    noDriver: 'No driver',
    assign: 'Assign',
    driversDirectory: 'Drivers Directory',
    contact: 'Contact',
    noDrivers: 'No registered drivers',
    active: 'Active',
    inactive: 'Inactive',
    printRoutesDesc: 'Check assigned routes for drivers to print.',
    from: 'From',
    to: 'To',
    print: 'Print',
    hotelRoute: 'Hotel / Route',
    service: 'Service',
    noBookingsFound: 'No bookings found with these filters',
    editDriver: 'Edit Driver',
    driverName: 'Driver name',
    whatsappPhone: 'WhatsApp / Phone',
    driverActive: 'Active driver (available for assignments)',
    assignDriver: 'Assign driver',
    pickupTime: 'Pickup time',
    driverPaymentUsd: 'Driver payment (US$)',
    saveAssignment: 'Save assignment',
    deleteDriverTitle: 'Delete driver?',
    deleteDriverText: 'This action cannot be undone and will unlink their assignments.',
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    enterCredentials: 'Enter your credentials to access the panel.',
    entering: 'Entering',
    enterPanel: 'Enter panel',
    loginError: 'Invalid credentials.',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Bookings',
    moduleOrders: 'Orders',
    moduleSchedule: 'Schedule',
    moduleActivities: 'Activities',
    moduleCustomers: 'Customers',
    moduleDrivers: 'Drivers',
    moduleProviders: 'Providers',
    moduleAgencies: 'Agencies',
    moduleFinances: 'Finances',
    moduleAudit: 'Audit',
    moduleUsers: 'Users',
    moduleSettings: 'Settings',
    notifWelcome: '🎉 Welcome to Jhoraji Tours. Your panel is ready.',
    notifFinance: '📊 Monthly financial report available in Finances.',
    notifSchedule: '📅 You have {count} bookings scheduled for today.',
    notifScheduleItems: '📅 {count} service(s) scheduled for today.',
    notifDriver: '🚗 Driver "{name}" assigned to airport transfer.',
    notifCustomer: '👤 New customer registered: {name}.',
    notifCustomerBase: '👤 Your customer base has {count} record(s).',
    notifPaymentDone: '✅ Booking #{ref} marked as paid.',
    notifPendingPayments: '💳 You have {count} pending payment bookings.',
    notifTour: '🏝️ Tour "{name}" activated on the web.',
    notifNewOrder: '📦 New order for {client}.',
    notifNewCustomerManual: '👤 New customer: {name}.',
    notifNewBooking: '📅 New booking: {ref}.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('jhoraji_language') || 'es');

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('jhoraji_language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    if (translations[lang]) setLanguage(lang);
  };

  const t = (key, args = {}) => {
    let str = translations[language]?.[key] || translations.es[key] || key;
    if (typeof str === 'string') {
      Object.keys(args).forEach(k => {
        str = str.replace(`{${k}}`, args[k]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
