/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  es: {
    dashboard: 'Dashboard',
    bookings: 'Reservas',
    tours: 'Excursiones',
    customers: 'Clientes',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    adminPanel: 'Panel de administración',
    notifications: 'Notificaciones',
    seeAll: 'Ver todas',
    myProfile: 'Mi Perfil',
    general: 'General',
    appearance: 'Apariencia',
    security: 'Seguridad',
    profile: 'Perfil',
    search: 'Buscar',
    actions: 'Acciones',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    create: 'Crear',
    update: 'Actualizar',
    active: 'Activo',
    inactive: 'Inactivo',
    all: 'Todas',
    paid: 'Pagado',
    pending: 'Pendiente',
    canceled: 'Cancelado',
    new: 'Nuevo',
    vip: 'VIP',
    status: 'Estado',
    customer: 'Cliente',
    customersTitle: 'Gestión de Clientes',
    customersSubtitle: 'Directorio de clientes e historial de reservas.',
    newCustomer: 'Nuevo Cliente',
    editCustomer: 'Editar Cliente',
    customerProfile: 'Perfil del Cliente',
    customerSaved: 'Cliente guardado correctamente',
    customerDeleted: 'Cliente eliminado',
    fullName: 'Nombre completo',
    contact: 'Contacto',
    country: 'País',
    countryOrigin: 'País de origen',
    totalBookings: 'Total de reservas',
    totalSpent: 'Total gastado',
    lastVisit: 'Última visita',
    searchCustomers: 'Buscar por nombre, email o país...',
    deleteCustomerTitle: '¿Eliminar Cliente?',
    deleteCustomerText: 'Esta acción borrará el cliente seleccionado. ¿Estás seguro?',
    bookingsTitle: 'Gestión de Reservas',
    bookingsSubtitle: 'Administra todas las reservas del sistema contable.',
    newBooking: 'Nueva Reserva',
    editBooking: 'Editar Reserva',
    bookingDetail: 'Detalle de Reserva',
    bookingSaved: 'Reserva guardada correctamente',
    bookingDeleted: 'Reserva eliminada',
    searchBookings: 'Buscar reservas...',
    bookingId: 'ID',
    tour: 'Tour',
    date: 'Fecha',
    pax: 'Pax',
    people: 'Personas',
    hotel: 'Hotel',
    amount: 'Monto',
    totalAmount: 'Monto total',
    notes: 'Notas',
    noNotes: 'Sin notas adicionales.',
    customerName: 'Nombre Cliente',
    paymentStatus: 'Estado Pago',
    pickup: 'Hotel / Recogida',
    saveBooking: 'Guardar Reserva',
    deleteBookingTitle: '¿Eliminar Reserva?',
    deleteBookingText: 'Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar la reserva',
    toursTitle: 'Gestión de Excursiones',
    toursSubtitle: 'Añade, edita o desactiva los tours disponibles en la web.',
    newTour: 'Nuevo Tour',
    editTour: 'Editar Tour',
    tourSaved: 'Tour guardado correctamente',
    tourDeleted: 'Tour eliminado correctamente',
    tourStatusUpdated: 'Estado del tour actualizado',
    searchTours: 'Buscar excursión...',
    category: 'Categoría',
    duration: 'Duración',
    rating: 'Calificación',
    adultPrice: 'Precio Adulto',
    childPrice: 'Precio Niño',
    imageUrl: 'URL de imagen',
    description: 'Descripción',
    includes: 'Incluye',
    title: 'Título',
    island: 'Isla',
    adventure: 'Aventura',
    culture: 'Cultura',
    nature: 'Naturaleza',
    halfDay: 'Medio Día',
    fullDay: 'Día Completo',
    deleteTourTitle: '¿Eliminar Tour?',
    deleteTourText: 'Esta acción no se puede deshacer. Se ocultará de la web principal.',
    systemPreferences: 'Administra las preferencias del sistema y tu cuenta.',
    companyInfo: 'Información de la Empresa',
    companyName: 'Nombre de la Empresa',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    website: 'Sitio Web',
    currency: 'Moneda Principal',
    saveChanges: 'Guardar Cambios',
    visualCustomization: 'Personalización Visual',
    systemTheme: 'Tema del Sistema',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    darkModeDesc: 'Cambia la apariencia del panel a colores oscuros.',
    primaryColor: 'Color Principal',
    panelLanguage: 'Idioma del Panel',
    panelLanguageDesc: 'Elige el idioma de la interfaz del sistema.',
    spanish: 'Español',
    english: 'English',
    notifPreferences: 'Preferencias de Notificación',
    accountSecurity: 'Seguridad de la Cuenta',
    activeSessions: 'Sesiones Activas',
    currentSession: 'Actual',
    closeSession: 'Cerrar Sesión',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Nueva Contraseña',
    updatePassword: 'Actualizar Contraseña',
    passwordUpdated: 'Contraseña actualizada correctamente',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres',
    currentPasswordRequired: 'Escribe la contraseña actual',
    preferenceUpdated: 'Preferencia actualizada',
    colorUpdated: 'Color actualizado',
    changesSaved: 'Cambios guardados',
    sessionClosed: 'Sesión cerrada',
    role: 'Cargo',
    department: 'Departamento',
    lastAccess: 'Último acceso',
    accessLevel: 'Nivel de acceso',
    accountData: 'Datos de la cuenta',
    emailNotifications: 'Notificaciones por Email',
    emailNotificationsDesc: 'Recibe un correo diario con el resumen de reservas.',
    newBookingAlerts: 'Alertas de Nueva Reserva',
    newBookingAlertsDesc: 'Notificación instantánea cuando un cliente hace una reserva.',
    paymentAlerts: 'Alertas de Pago',
    paymentAlertsDesc: 'Avisos cuando se confirma un pago mediante tarjeta.',
    pushNotifications: 'Notificaciones Push',
    pushNotificationsDesc: 'Notificaciones en el navegador.',
    browserPermissionGranted: 'Permiso de notificaciones activado',
    browserPermissionDenied: 'El navegador no permitió las notificaciones',
    browserPermissionUnsupported: 'Este navegador no soporta notificaciones push',
    dashboardSummary: 'Resumen del Panel',
    dashboardWelcome: 'Bienvenido de nuevo, aquí tienes el estado de Jhoraji Tours.',
    downloadReport: 'Descargar Reporte',
    reportGenerated: 'Reporte generado exitosamente',
    totalRevenue: 'Ingresos Totales',
    todayBookings: 'Reservas Hoy',
    newCustomers: 'Nuevos Clientes',
    activeTours: 'Tours Activos',
    thisMonth: 'este mes',
    recentBookings: 'Reservas Recientes',
    popularTours: 'Excursiones Populares',
    loginSubtitle: 'Sistema de Reservas y Contabilidad',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    login: 'Iniciar Sesión',
    loginSuccess: 'Inicio de sesión exitoso',
    loginError: 'Correo o contraseña incorrectos. Por favor, intenta de nuevo.',
    forgotCredentials: '¿Olvidaste tus credenciales?',
    contactSupport: 'Contacta al soporte técnico',
    usdCurrency: 'USD - Dólar Estadounidense',
    eurCurrency: 'EUR - Euro',
    dopCurrency: 'DOP - Peso Dominicano',
    sales: 'ventas',
    noCustomersFound: 'No se encontraron clientes.',
    permissions: 'Permisos',
    permissionsDesc: 'Gestiona el acceso a los módulos según el rol.',
    selectCountry: 'Seleccione un país',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Reservas',
    moduleTours: 'Excursiones',
    moduleCustomers: 'Clientes',
    moduleSettings: 'Configuración',
    roleOperator: 'Operador de Reservas',
    roleAgent: 'Agente de Ventas',
    moduleAccess: 'Acceso a Módulos',
    actionPermissions: 'Permisos de Acciones',
    actionCreate: 'Crear registros',
    actionEdit: 'Editar registros',
    actionDelete: 'Eliminar registros',
    showing: 'Mostrando',
    to: 'a',
    of: 'de',
    previous: 'Anterior',
    next: 'Siguiente',
    moduleUsers: 'Usuarios',
    moduleDrivers: 'Choferes',
    moduleProviders: 'Proveedores y Actividades',
  },
  en: {
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    tours: 'Tours',
    customers: 'Customers',
    settings: 'Settings',
    logout: 'Log Out',
    adminPanel: 'Admin panel',
    notifications: 'Notifications',
    seeAll: 'See all',
    myProfile: 'My Profile',
    general: 'General',
    appearance: 'Appearance',
    security: 'Security',
    profile: 'Profile',
    search: 'Search',
    actions: 'Actions',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    create: 'Create',
    update: 'Update',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    paid: 'Paid',
    pending: 'Pending',
    canceled: 'Canceled',
    new: 'New',
    vip: 'VIP',
    status: 'Status',
    customer: 'Customer',
    customersTitle: 'Customer Management',
    customersSubtitle: 'Customer directory and booking history.',
    newCustomer: 'New Customer',
    editCustomer: 'Edit Customer',
    customerProfile: 'Customer Profile',
    customerSaved: 'Customer saved successfully',
    customerDeleted: 'Customer deleted',
    fullName: 'Full name',
    contact: 'Contact',
    country: 'Country',
    countryOrigin: 'Country of origin',
    totalBookings: 'Total bookings',
    totalSpent: 'Total spent',
    lastVisit: 'Last visit',
    searchCustomers: 'Search by name, email or country...',
    deleteCustomerTitle: 'Delete Customer?',
    deleteCustomerText: 'This action will remove the selected customer. Are you sure?',
    bookingsTitle: 'Booking Management',
    bookingsSubtitle: 'Manage all accounting system bookings.',
    newBooking: 'New Booking',
    editBooking: 'Edit Booking',
    bookingDetail: 'Booking Detail',
    bookingSaved: 'Booking saved successfully',
    bookingDeleted: 'Booking deleted',
    searchBookings: 'Search bookings...',
    bookingId: 'ID',
    tour: 'Tour',
    date: 'Date',
    pax: 'Pax',
    people: 'People',
    hotel: 'Hotel',
    amount: 'Amount',
    totalAmount: 'Total amount',
    notes: 'Notes',
    noNotes: 'No additional notes.',
    customerName: 'Customer Name',
    paymentStatus: 'Payment Status',
    pickup: 'Hotel / Pickup',
    saveBooking: 'Save Booking',
    deleteBookingTitle: 'Delete Booking?',
    deleteBookingText: 'This action cannot be undone. Are you sure you want to delete booking',
    toursTitle: 'Tour Management',
    toursSubtitle: 'Add, edit or disable tours available on the website.',
    newTour: 'New Tour',
    editTour: 'Edit Tour',
    tourSaved: 'Tour saved successfully',
    tourDeleted: 'Tour deleted successfully',
    tourStatusUpdated: 'Tour status updated',
    searchTours: 'Search tour...',
    category: 'Category',
    duration: 'Duration',
    rating: 'Rating',
    adultPrice: 'Adult Price',
    childPrice: 'Child Price',
    imageUrl: 'Image URL',
    description: 'Description',
    includes: 'Includes',
    title: 'Title',
    island: 'Island',
    adventure: 'Adventure',
    culture: 'Culture',
    nature: 'Nature',
    halfDay: 'Half Day',
    fullDay: 'Full Day',
    deleteTourTitle: 'Delete Tour?',
    deleteTourText: 'This action cannot be undone. It will be hidden from the website.',
    systemPreferences: 'Manage system preferences and your account.',
    companyInfo: 'Company Information',
    companyName: 'Company Name',
    email: 'Email Address',
    phone: 'Phone Number',
    website: 'Website',
    currency: 'Main Currency',
    saveChanges: 'Save Changes',
    visualCustomization: 'Visual Customization',
    systemTheme: 'System Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    darkModeDesc: 'Change the panel appearance to dark colors.',
    primaryColor: 'Primary Color',
    panelLanguage: 'Panel Language',
    panelLanguageDesc: 'Choose the interface language of the system.',
    spanish: 'Spanish',
    english: 'English',
    notifPreferences: 'Notification Preferences',
    accountSecurity: 'Account Security',
    activeSessions: 'Active Sessions',
    currentSession: 'Current',
    closeSession: 'Close Session',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated successfully',
    passwordsDontMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    currentPasswordRequired: 'Enter the current password',
    preferenceUpdated: 'Preference updated',
    colorUpdated: 'Color updated',
    changesSaved: 'Changes saved',
    sessionClosed: 'Session closed',
    role: 'Role',
    department: 'Department',
    lastAccess: 'Last access',
    accessLevel: 'Access level',
    accountData: 'Account details',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Receive a daily email with the bookings summary.',
    newBookingAlerts: 'New Booking Alerts',
    newBookingAlertsDesc: 'Instant notification when a customer makes a booking.',
    paymentAlerts: 'Payment Alerts',
    paymentAlertsDesc: 'Alerts when a card payment is confirmed.',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Browser notifications.',
    browserPermissionGranted: 'Notification permission enabled',
    browserPermissionDenied: 'The browser did not allow notifications',
    browserPermissionUnsupported: 'This browser does not support push notifications',
    dashboardSummary: 'Dashboard Summary',
    dashboardWelcome: 'Welcome back, here is the status of Jhoraji Tours.',
    downloadReport: 'Download Report',
    reportGenerated: 'Report generated successfully',
    totalRevenue: 'Total Revenue',
    todayBookings: 'Bookings Today',
    newCustomers: 'New Customers',
    activeTours: 'Active Tours',
    thisMonth: 'this month',
    recentBookings: 'Recent Bookings',
    popularTours: 'Popular Tours',
    loginSubtitle: 'Booking and Accounting System',
    password: 'Password',
    rememberMe: 'Remember me',
    login: 'Log In',
    loginSuccess: 'Login successful',
    loginError: 'Incorrect email or password. Please try again.',
    forgotCredentials: 'Forgot your credentials?',
    contactSupport: 'Contact technical support',
    usdCurrency: 'USD - US Dollar',
    eurCurrency: 'EUR - Euro',
    dopCurrency: 'DOP - Dominican Peso',
    sales: 'sales',
    noCustomersFound: 'No customers found.',
    permissions: 'Permissions',
    permissionsDesc: 'Manage access to modules based on role.',
    selectCountry: 'Select a country',
    moduleDashboard: 'Dashboard',
    moduleBookings: 'Bookings',
    moduleTours: 'Tours',
    moduleCustomers: 'Customers',
    moduleSettings: 'Settings',
    roleOperator: 'Booking Operator',
    roleAgent: 'Sales Agent',
    moduleAccess: 'Module Access',
    actionPermissions: 'Action Permissions',
    actionCreate: 'Create records',
    actionEdit: 'Edit records',
    actionDelete: 'Delete records',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    moduleUsers: 'Users',
    moduleDrivers: 'Drivers',
    moduleProviders: 'Providers & Activities',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('jhoraji_language') || 'es');

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('jhoraji_language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    if (translations[lang]) setLanguage(lang);
  };

  const t = (key) => translations[language]?.[key] || translations.es[key] || key;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
